import { createRequire } from 'node:module';
import { access, readFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
const require = createRequire(import.meta.url);
const asar = require('@electron/asar');
const entries = asar.listPackage('release/linux-unpacked/resources/app.asar');
for (const entry of ['/main.cjs', '/preload.cjs', '/iptv.cjs', '/vault.cjs', '/licenses/saxes-LICENSE.txt', '/licenses/xmlchars-LICENSE.txt']) assert(entries.includes(entry), `Packaged app is missing ${entry}`);
assert(!entries.some(entry => entry.includes('node_modules') || entry.includes('provider.enc')), 'Unexpected runtime contents');
const prefix = 'release/linux-unpacked/resources/public/preview/';
for (const file of ['index.html', 'preview.js', 'preview.css', 'iptv-runtime.js', 'hls.min.js', 'mpegts.js', 'tv-runtime.js', 'fieldscreen-mark.png', 'HLS-LICENSE.txt', 'MPEGTS-LICENSE.txt']) await access(prefix + file);
assert((await readFile(prefix + 'index.html', 'utf8')).includes('./iptv-runtime.js'));
console.log('Packaged IPTV service, guide parser, players, licenses, and UI are present.');
